<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\ProductoController;
use App\Http\Controllers\Admin\ReclamoController;
use App\Http\Controllers\Admin\UsuarioController;
use App\Http\Controllers\Admin\TiendaController;
use App\Http\Controllers\Admin\CanalController;
use App\Http\Controllers\Admin\ConceptoController;
use App\Http\Controllers\Admin\DocumentoController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\RedController;
use App\Http\Controllers\Admin\DepartamentoController;
use App\Http\Controllers\Admin\ProvinciaController;
use App\Http\Controllers\Admin\DistritoController;
use App\Http\Controllers\Admin\BanerController;
use App\Http\Controllers\Admin\PublicidadController;
use App\Http\Controllers\Admin\RapidaController;
use App\Http\COntrollers\Admin\DetallebanerController;
use App\Http\COntrollers\Admin\ColorController;
use App\Http\COntrollers\Admin\fitController;
use App\Http\COntrollers\Admin\MarcaController;
use App\Http\COntrollers\Admin\TallaController;
use App\Http\COntrollers\Admin\TipoController;
use App\Http\COntrollers\Admin\EmpresaController;
use App\Http\COntrollers\Admin\SuscriptorController;
use App\Http\Controllers\Admin\FotoController;
use App\Http\Controllers\Admin\ReclamoPdfController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->get('/', [HomeController::class, 'index'])->name('admin.home');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->get('/reporte/{id}', [ReclamoPdfController::class, 'downloadPDF'])->name('reporte.reclamo');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('productos', ProductoController::class)->names('admin.productos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('reclamos', ReclamoController::class)->names('admin.reclamos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('usuarios', UsuarioController::class)->names('admin.usuarios');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('tiendas', TiendaController::class)->names('admin.tiendas');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('canals', CanalController::class)->names('admin.canals');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('conceptos', ConceptoController::class)->names('admin.conceptos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('documentos', DocumentoController::class)->names('admin.documentos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('categorias', CategoriaController::class)->names('admin.categorias');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('sliders', SliderController::class)->names('admin.sliders');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('reds', RedController::class)->names('admin.reds');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('departamentos', DepartamentoController::class)->names('admin.departamentos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('provincias', ProvinciaController::class)->names('admin.provincias');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('distritos', DistritoController::class)->names('admin.distritos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('baners', BanerController::class)->names('admin.baners');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('publicidads', PublicidadController::class)->names('admin.publicidads');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('rapidas', RapidaController::class)->names('admin.rapidas');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('detallebaners', DetallebanerController::class)->names('admin.detallebaners');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('colors', ColorController::class)->names('admin.colors');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('fits', FitController::class)->names('admin.fits');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('marcas', MarcaController::class)->names('admin.marcas');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('tallas', TallaController::class)->names('admin.tallas');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('tipos', TipoController::class)->names('admin.tipos');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('empresas', EmpresaController::class)->names('admin.empresas');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('suscriptors', SuscriptorController::class)->names('admin.suscriptors');
Route::middleware(['auth:sanctum', 'verified', 'verifyrole'])->resource('fotos', FotoController::class)->names('admin.fotos');